### ISSUE TITLE
大佬太强了，给大家分享一个抓t的办法

### ISSUE THREAD

**Issue by hwhaocool** [Lcry/a-sheep-assistant#40]
平台： Windows
软件： pc微信、clash、charles 或者 fiddler
方法：https://www.52pojie.cn/forum.php?mod=redirect&goto=findpost&ptid=1681028&pid=43973728

步骤：
1. `clash` 安装 `service mode`， 再安装 `tun mode`
2. `clash` `profiles` 修改配置(复制帖子里的内容，直接`追加`就行)
3. 重启pc微信，打开小程序，就可以看到https的包了，`t`在Header里

**Comment by hwhaocool** [comment]
![image](https://user-images.githubusercontent.com/20699977/190453054-8488068e-0a47-4a9e-8233-86e853d681e2.png)
![image](https://user-images.githubusercontent.com/20699977/190453248-b9121150-602d-431e-b678-b9a4209baa4a.png)
![image](https://user-images.githubusercontent.com/20699977/190453517-4dc446a6-8387-462e-9d87-f25ccbf556f0.png)

**Comment by wjx-wiki** [comment]
@Lcry 你微信版本多少呀？我咋抓不到呢

**Comment by HClO-LUO** [comment]
![image](https://user-images.githubusercontent.com/111284355/190463270-a62332e2-dd7b-4f50-8371-5f78b4dda8af.png)
大佬 我这个啥情况啊

**Comment by HClO-LUO** [comment]
![image](https://user-images.githubusercontent.com/111284355/190463557-0ff9298f-fea7-4836-b65a-663206d40c86.png)
an'zhuang'hu安装环境也有问题

**Comment by DancingLeaf123** [comment]
> 

请问这个clash 的port是该8888和fiddler一样呢，还是不一样。 另外这个 profiles修改是修改那个本身的，还是代理的
![Uploading image.png…]()

**Comment by DancingLeaf123** [comment]
多谢兄弟，安装你的改了之后，选择本地的yaml. 然后选全局direct, 能抓到t了

**Comment by DancingLeaf123** [comment]
![73d852635ceb35a9dbfff423e729320](https://user-images.githubusercontent.com/23498471/190473801-7bbd6013-e8d1-4495-9136-4e52aa3e02bc.jpg)
再也不用受气了

**Comment by HClO-LUO** [comment]
> ![73d852635ceb35a9dbfff423e729320](https://user-images.githubusercontent.com/23498471/190473801-7bbd6013-e8d1-4495-9136-4e52aa3e02bc.jpg) 再也不用受气了

大佬帮帮我

**Comment by HClO-LUO** [comment]
> > ![73d852635ceb35a9dbfff423e729320](https://user-images.githubusercontent.com/23498471/190473801-7bbd6013-e8d1-4495-9136-4e52aa3e02bc.jpg) 再也不用受气了
> 
> 大佬帮帮我

我不知道为什么 一运行全报错

**Comment by HClO-LUO** [comment]
![image](https://user-images.githubusercontent.com/111284355/190474434-546c99a9-6507-4af7-be3d-4e5794b51776.png)

然后他说的那个环境我也搞不好

**Comment by DancingLeaf123** [comment]
1.跑的时候关掉fiddler或者抓包软件，抓到t之后就关掉抓包软件

**Comment by yanpengqing** [comment]
> 1.跑的时候关掉fiddler或者抓包软件，抓到t之后就关掉抓包软件

端口是8888还是8877？

**Comment by chasansui0522** [comment]
高版本的wx 比如3.7以上的是不是不让抓了

**Comment by P1an8** [comment]
试了一下，不行。。微信版本是最新的

**Comment by yangtzelsl** [comment]
链接里的 clash profile 能否分享一下，吾爱破解不能免费注册，看不到profile文件

**Comment by iHx-rainbow** [comment]
@yangtzelsl 
```
proxies:
  - name: Fiddler
    type: http
    server: 127.0.0.1
    port: 8888
proxy-groups:
  - name: Proxy
    proxies: 
      - Fiddler
    type: select
rules:
  - PROCESS-NAME,Fiddler.exe,DIRECT
  - PROCESS-NAME,WeChat.exe,Fiddler
  - PROCESS-NAME,WeChatAppEx.exe,Fiddler
  - MATCH,DIRECT
```
